### ISSUE TITLE
problem with flickr embed

### ISSUE THREAD

**Issue by ghost** [starfishmod/jquery-oembed-all#37]
Hi!

can't seem to make the embed work with this flickr URL: http://www.flickr.com/photos/10130880@N03/3987337362/

i'm testing here: http://footeste.info/oembed/

am i doing something wrong?

thanks!
rui

**Comment by starfishmod** [comment]
This looks like a flickr issue. Other flickr URL's work fine. I'm not sure but maybe flickr blocks some photos from embedding? or maybe flickr takes a few day to have photos work under oEmbed? I notice that other parts of the same photostream don't work either.

To be honest I'm not sure - ironically enough this would have probably work if I switch to OGP instead of oEmbed. Perhaps I should set up an OGP fall-back on bad oEmbed requests....

**Comment by ghost** [comment]
yes, it works with all other flickr photos.. 

it's not your issue:
in the source, meta-tags:
<code>meta name="pinterest" content="nopin" description="You can't share this photo because the owner has disabled access from 3rd party sites (through the Flickr API)."</code>

**Comment by retani** [comment]
I think, this is a more complicated issue. See the following examples:

http://www.flickr.com/photos/23264080@N00/512324715/   (Baby, works)
http://www.flickr.com/photos/23264080@N00/521773348/   (Balcony, does not work)

Same result when using the noembed.com demo! Check the following links:

http://noembed.com/demo?url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2F23264080%40N00%2F512324715%2F
http://noembed.com/demo?url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2F23264080%40N00%2F521773348%2F

I cannot figure out any difference in the configurations of these 2 images.
